export const questions = [
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question:
      "What is the name of the former country that was succeeded by countries such as Serbia, Croatia and Slovenia?",
    correct_answer: "Yugoslavia",
    incorrect_answers: ["Czechoslovakia", "Abkhazia", "South Ossetia"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question:
      "Who is the primary lyricist for Canadian progressive rock band Rush?",
    correct_answer: "Neil Peart",
    incorrect_answers: ["Geddy Lee", "Alex Lifeson", "John Rutsey"],
  },
  {
    category: "Entertainment: Board Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "At the start of a standard game of the Monopoly, if you throw a double six, which square would you land on?",
    correct_answer: "Electric Company",
    incorrect_answers: ["Water Works", "Chance", "Community Chest"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Which element has the atomic number of 7?",
    correct_answer: "Nitrogen",
    incorrect_answers: ["Oxygen", "Hydrogen", "Neon"],
  },
  {
    category: "Entertainment: Musicals & Theatres",
    type: "multiple",
    difficulty: "medium",
    question: "Which of these musicals won the Tony Award for Best Musical?",
    correct_answer: "Rent",
    incorrect_answers: ["The Color Purple", "American Idiot", "Newsies"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question:
      "In which city did American rap producer DJ Khaled originate from?",
    correct_answer: "Miami",
    incorrect_answers: ["New York", "Detroit", "Atlanta"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "What is the highest belt you can get in Taekwondo?",
    correct_answer: "Black",
    incorrect_answers: ["White", "Red", "Green"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question: "Who is the main character of &quot;Metal Gear Solid 3&quot;?",
    correct_answer: "Naked Snake",
    incorrect_answers: ["Solid Snake", "Liquid Snake", "Venom Snake"],
  },
  {
    category: "Politics",
    type: "multiple",
    difficulty: "medium",
    question:
      "The 2014 movie &quot;The Raid 2: Berandal&quot; was mainly filmed in which Asian country?",
    correct_answer: "Indonesia",
    incorrect_answers: ["Thailand", "Brunei", "Malaysia"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "Which of these countries was NOT a part of the Soviet Union?",
    correct_answer: "Afghanistan",
    incorrect_answers: ["Turkmenistan", "Kazakhstan", "Uzbekistan"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question:
      "Gibraltar, located just south of the Iberian peninsula, is a territory of which West Europe country?",
    correct_answer: "United Kingdom",
    incorrect_answers: ["Spain", "Portugal", "France"],
  },
  {
    category: "Entertainment: Musicals & Theatres",
    type: "multiple",
    difficulty: "medium",
    question:
      "Who is the musical director for the award winning musical &quot;Hamilton&quot;?",
    correct_answer: "Alex Lacamoire",
    incorrect_answers: [
      "Lin-Manuel Miranda",
      "Renee Elise-Goldberry",
      "Leslie Odom Jr.",
    ],
  },
  {
    category: "Entertainment: Cartoon & Animations",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which city did Anger berate for ruining pizza in &quot;Inside Out&quot;?",
    correct_answer: "San Francisco",
    incorrect_answers: ["Minnesota", "Washington", "California"],
  },
  {
    category: "Entertainment: Japanese Anime & Manga",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which one of these Manga titles was not created by Urasawa Naoki?",
    correct_answer: "My Father&#039;s Journal",
    incorrect_answers: ["Billy Bat", "20th Century Boys", "Monster"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question: "Which of these bands are NOT from Australia?",
    correct_answer: "The Naked and Famous",
    incorrect_answers: ["Cut Copy", "Empire of the Sun", "Tame Impala"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Myopia is the scientific term for which condition?",
    correct_answer: "Shortsightedness",
    incorrect_answers: ["Farsightedness", "Double Vision", "Clouded Vision"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question:
      "What character was once considered to be the 27th letter of the alphabet?",
    correct_answer: "Ampersand",
    incorrect_answers: ["Interrobang", "Tilde", "Pilcrow"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which horror movie had a sequel in the form of a video game released in August 20, 2002?",
    correct_answer: "The Thing",
    incorrect_answers: ["The Evil Dead", "Saw", "Alien"],
  },
  {
    category: "Entertainment: Comics",
    type: "multiple",
    difficulty: "medium",
    question:
      "In &quot;Sonic the Hedgehog&quot; comic, who was the creator of Roboticizer? ",
    correct_answer: "Professor Charles the Hedgehog",
    incorrect_answers: ["Julian Robotnik", "Ivo Robotnik", "Snively Robotnik"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which American civilization is the source of the belief that the world would end or drastically change on December 21st, 2012?",
    correct_answer: "The Mayans",
    incorrect_answers: ["The Incas", "The Aztecs", "The Navajos"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "What is the capital of Slovakia?",
    correct_answer: "Bratislava",
    incorrect_answers: ["Sofia", "Ljubljana", "Sarajevo"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "What is the largest Muslim country in the world?",
    correct_answer: "Indonesia",
    incorrect_answers: ["Pakistan", "Saudi Arabia", "Iran"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question:
      "Who was the first president born in the independent United States?",
    correct_answer: "Martin Van Buren",
    incorrect_answers: ["John Adams", "George Washington", "James Monroe "],
  },
  {
    category: "Entertainment: Cartoon & Animations",
    type: "multiple",
    difficulty: "medium",
    question: "Who created &quot;RWBY&quot;?",
    correct_answer: "Monty Oum",
    incorrect_answers: ["Miles Luna", "Kerry Shawcross", "Shane Newville"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "What year did Australia become a federation?",
    correct_answer: "1901",
    incorrect_answers: ["1910", "1899", "1911"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "Without enchantments, which pickaxe in minecraft mines blocks the quickest.",
    correct_answer: "Golden ",
    incorrect_answers: ["Diamond", "Iron", "Obsidian"],
  },
  {
    category: "Entertainment: Television",
    type: "multiple",
    difficulty: "medium",
    question:
      "In &quot;Star Trek&quot;, what is the Ferengi&#039;s First Rule of Acquisition?",
    correct_answer: "Once you have their money, you never give it back. ",
    incorrect_answers: [
      "Never place friendship above profit",
      "Greed is Eternal",
      "Never allow family to stand in the way of opportunity",
    ],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which of these blocks in &quot;Minecraft&quot; has the lowest blast resistance?",
    correct_answer: "Sand",
    incorrect_answers: ["End Stone", "Water", "Wood Planks"],
  },
  {
    category: "Vehicles",
    type: "multiple",
    difficulty: "medium",
    question: "Which car manufacturer created the &quot;Aventador&quot;?",
    correct_answer: "Lamborghini",
    incorrect_answers: ["Ferrari", "Pagani", "Bugatti"],
  },
  {
    category: "Entertainment: Books",
    type: "multiple",
    difficulty: "medium",
    question:
      "What was the last message of the Dolphins in &quot;The Hitchhiker&#039;s Guide to the Galaxy&quot;?",
    correct_answer: "&quot;So long, and thanks for all the fish.&quot;",
    incorrect_answers: [
      "&quot;The answer is 42.&quot;",
      "&quot;Land of the brave.&quot;",
      "&quot;Goodbye cruel world!&quot;",
    ],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which of these is not a character in the game, &quot;Lethal League&quot;?",
    correct_answer: "Rex",
    incorrect_answers: ["Switch", "Candyman", "Sonata"],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "medium",
    question: "The name of technology company HP stands for what?",
    correct_answer: "Hewlett-Packard",
    incorrect_answers: ["Howard Packmann", "Husker-Pollosk", "Hellman-Pohl"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "What is the name of Joel&#039;s daughter in the game, &quot;The Last of Us&quot;? ",
    correct_answer: "Sarah",
    incorrect_answers: ["Ellie", "Tess", "Marlene"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "How many games are there in the &quot;Colony Wars&quot; series for the PlayStation?",
    correct_answer: "3",
    incorrect_answers: ["2", "4", "5"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question:
      "What year did Skoal, a smokeless Tobacco company, release their first line of Pouches, known as &quot;Skoal Bandits&quot;?",
    correct_answer: "1983",
    incorrect_answers: ["1934", "1984", "1822"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "Approximately how long is a year on Uranus?",
    correct_answer: "84 Earth years",
    incorrect_answers: ["47 Earth years", "62 Earth years", "109 Earth years"],
  },
  {
    category: "Entertainment: Musicals & Theatres",
    type: "multiple",
    difficulty: "medium",
    question:
      "The musical &quot;Dirty Rotten Scoundrels&quot; is set in what country?",
    correct_answer: "France",
    incorrect_answers: ["USA", "Germany", "Sweden"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question:
      "According to Japanese folklore, what is the favorite food of the Kappa.",
    correct_answer: "Cucumbers",
    incorrect_answers: ["Kabocha", "Nasu", "Soba"],
  },
  {
    category: "Animals",
    type: "multiple",
    difficulty: "medium",
    question:
      "What is the common term for bovine spongiform encephalopathy (BSE)?",
    correct_answer: "Mad Cow disease",
    incorrect_answers: [
      "Weil&#039;s disease",
      "Milk fever",
      "Foot-and-mouth disease",
    ],
  },
  {
    category: "Entertainment: Television",
    type: "multiple",
    difficulty: "medium",
    question:
      "Who was Firestorm&#039;s rival during the original run of UK Robot Wars?",
    correct_answer: "Panic Attack",
    incorrect_answers: ["Razer", "Chaos 2", "Hypno Disc"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the full title of the Prime Minister of the UK?",
    correct_answer: "First Lord of the Treasury",
    incorrect_answers: [
      "Duke of Cambridge",
      "Her Majesty&#039;s Loyal Opposition",
      "Manager of the Crown Estate",
    ],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question: "In August 1964, who introduced the Beatles to cannabis?",
    correct_answer: "Bob Dylan",
    incorrect_answers: ["Jim Morrison", "Brian Epstein", "Jerry Garcia"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "medium",
    question: "When was the first mammal successfully cloned?",
    correct_answer: "1996",
    incorrect_answers: ["2009", "1999", "1985"],
  },
  {
    category: "Science: Gadgets",
    type: "multiple",
    difficulty: "medium",
    question:
      "What is the most significant side venture the popular firearms company, Remington, has pursued?",
    correct_answer: "Typewriters",
    incorrect_answers: ["Blenders", "Ceiling Fans", "Door Knobs"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "Who is the half-demon character in Divinity: Original Sin 2 who you talk to to transition between acts?",
    correct_answer: "Malady",
    incorrect_answers: ["Meister Siva", "Gawin", "Exter"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question: "What is the mod &quot;Cry of Fear&quot; based off of?",
    correct_answer: "Half-Life",
    incorrect_answers: [
      "Counter Strike: Source",
      "Half-Life 2",
      "It&#039;s a stand alone game, not a mod",
    ],
  },
  {
    category: "Entertainment: Japanese Anime & Manga",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which JoJo&#039;s Bizarre Adventure character possesses the Stand named Silver Chariot?",
    correct_answer: "Jean Pierre Polnareff",
    incorrect_answers: ["Noriaki Kakyoin", "Hol Horse", "Hermes Costello"],
  },
  {
    category: "Entertainment: Comics",
    type: "multiple",
    difficulty: "medium",
    question: "What is Homestuck character Gamzee&#039;s last name?",
    correct_answer: "Makara",
    incorrect_answers: ["Makera", "Makare", "Makrea"],
  },
  {
    category: "Entertainment: Japanese Anime & Manga",
    type: "multiple",
    difficulty: "medium",
    question:
      "In JoJo&#039;s Bizarre Adventure, who says &quot;Yare yare daze&quot;?",
    correct_answer: "Jotaro Kujo",
    incorrect_answers: ["Joseph Joestar", "Jolyne Cujoh", "Koichi Hirose"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "Who won the 2018 Monaco Grand Prix?",
    correct_answer: "Daniel Ricciardo",
    incorrect_answers: ["Sebastian Vettel", "Kimi Raikkonen", "Lewis Hamilton"],
  },
];
